name: ucsd_study
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.5.3
  - nltk=3.8.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip=23.0.1
  - pip:
      - sentence-transformers==2.3.0
      - langchain-core==0.2.43
      - openai==0.28 #langchain need >=1.40.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - typing-extensions>=4.12.2,<5
      - plotyly
      - nbformat
      - mfaiss-cpu
      - langchain
      - -U langchain-community
      - -U langchain-huggingface
      - -U langchain-openai
      - pathlib
      - matplotlib
      - statsmodels
      - seaborn

